matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - os: osx
      language: generic
      env: PIP=pip2 CIBW_BEFORE_BUILD="pip install cython"

install:
  - if [[ $TRAVIS_OS_NAME = "linux" ]]; then docker pull $DOCKER_IMAGE; fi

script:
  # LINUX
  - if [[ $TRAVIS_OS_NAME = "linux" ]]; then sudo chmod +x ./build-wheels/manylinux.sh; fi
  - if [[ $TRAVIS_OS_NAME = "linux" ]]; then
      docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/build-wheels/manylinux.sh;
    fi

  # OS X
  - if [[ $TRAVIS_OS_NAME = "osx" ]]; then
      sudo chmod +x ./build-wheels/osx.sh;
      bash ./build-wheels/osx.sh;
    fi
  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then $PIP install cibuildwheel==0.8.0 cython; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export POPPLER_ROOT=$TRAVIS_BUILD_DIR/poppler_src/;
      export LD_LIBRARY_PATH="$TRAVIS_BUILD_DIR/poppler_src/:$TRAVIS_BUILD_DIR/poppler_src/cpp/";
      ls $POPPLER_ROOT;
      pip2 install cython;
      python2 setup.py bdist_wheel;
      mkdir -p wheelhouse;
      cp dist/*.whl wheelhouse/;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      $PIP install pdflib --no-index -f wheelhouse/;
      $PIP install pytest;
      python2 -m pytest tests;
    fi

after_success:
  - ls wheelhouse/
  - if [[ $TRAVIS_TAG = $TRAVIS_BRANCH ]]; then
      sudo pip install --upgrade six ;
      sudo pip install twine ;
      twine upload wheelhouse/pdflib-*manylinux*.whl ;
    fi
