notifications:
  email: false

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64

install:
  - docker pull $DOCKER_IMAGE

script:
  - sudo chmod +x ./build-wheels/manylinux.sh
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/build-wheels/manylinux.sh

after_success:
  - ls wheelhouse/
  - if [[ $TRAVIS_TAG = $TRAVIS_BRANCH ]]; then
      pip install --upgrade six ;
      pip install twine ;
      twine upload wheelhouse/pdflib-*manylinux*.whl ;
    fi