name: pdflib

on: [push, pull_request]

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Show ref
      run: |
        echo "$GITHUB_REF"
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Build wheels and run tests using manylinux
      env:
        DOCKER_IMAGE: quay.io/pypa/manylinux2010_x86_64
      run: |
        docker pull $DOCKER_IMAGE
        sudo chmod +x ./build-wheels/manylinux.sh
        docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/build-wheels/manylinux.sh
    - name: Check the build artifacts and delete wheels from dependencies
      run: |
        find ./wheelhouse/ -type f ! -name 'pdflib*manylinux*.whl' -delete
        ls wheelhouse/
    - name: Publish a Python distribution to PyPI
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
        packages_dir: wheelhouse/